# Matrix Implementation in NumPy

#### It includes following operations:

#### 1) Matrix Properties

#### 2) Matrix Modification

#### 3) Arthimetic Operations on matrix

#### 4) Concepts of Linear Algebra
   
   a) Determinant of matrix
   
   b) Rank of matrix
   
   c) Inverse of a matrix
   
   d) Solution of linear equations

### Create a matrix

In [1]:
import numpy as np

In [2]:
matrix_1 =np.matrix("2,3,6;4,9,12;18,81,48")
print(matrix_1)

[[ 2  3  6]
 [ 4  9 12]
 [18 81 48]]


In [3]:
##Check datatype
type(matrix_1)

numpy.matrixlib.defmatrix.matrix

### Matrix Properties

In [4]:
## Check shape of a matrix
matrix_1.shape

(3, 3)

In [5]:
## Check number of elements in a matrix
matrix_1.size

9

In [6]:
##Access row and colummns of a matrix[row,column]
matrix_1[0, :]

matrix([[2, 3, 6]])

In [7]:
## Access particular element from its index
matrix_1[1,1]

9

In [8]:
matrix_1[1,0:2]

matrix([[4, 9]])

In [9]:
##Transpose of a matrix
print(matrix_1)
print()
print('Transpose of a matrix is :- \n', matrix_1.T)

[[ 2  3  6]
 [ 4  9 12]
 [18 81 48]]

Transpose of a matrix is :- 
 [[ 2  4 18]
 [ 3  9 81]
 [ 6 12 48]]


### Matrix modification

In [10]:
## Add new column in a matrix using insert()

col_new = np.matrix("1,2,3")
mat_ins = np.insert(matrix_1, 0,col_new, axis =1)

## Add new row in a matrix using insert()
mat_ins = np.insert(matrix_1, 0,col_new, axis =0)

print(mat_ins)

[[ 1  2  3]
 [ 2  3  6]
 [ 4  9 12]
 [18 81 48]]


### Arthimetic Operations on matrix

In [11]:
## Define two matrix
mat_1 = np.matrix("2,4,6; 9,12,21; 18,46,-34")
mat_2 = np.matrix("3,-4,9; 0,11,13; -18,16,17")

print(mat_1)
print()
print(mat_2)

[[  2   4   6]
 [  9  12  21]
 [ 18  46 -34]]

[[  3  -4   9]
 [  0  11  13]
 [-18  16  17]]


In [12]:
## Matrix Addition
np.add(mat_1, mat_2)

matrix([[  5,   0,  15],
        [  9,  23,  34],
        [  0,  62, -17]])

In [13]:
## Matrix Subtraction
np.subtract(mat_1, mat_2)

matrix([[ -1,   8,  -3],
        [  9,   1,   8],
        [ 36,  30, -51]])

In [14]:
## Matrix Multiplication
np.dot(mat_1, mat_2)

matrix([[-102,  132,  172],
        [-351,  432,  594],
        [ 666, -110,  182]])

In [15]:
## Elementwise Multiplication
np.multiply(mat_1, mat_2)

matrix([[   6,  -16,   54],
        [   0,  132,  273],
        [-324,  736, -578]])

In [16]:
## Matrix Division
np.divide(mat_2, mat_1)

matrix([[ 1.5       , -1.        ,  1.5       ],
        [ 0.        ,  0.91666667,  0.61904762],
        [-1.        ,  0.34782609, -0.5       ]])

### Concepts of Linear Algebra

In [17]:
## Determinant of matrix

np.linalg.det(mat_1)

1176.0

In [18]:
## Rank of Matrix :- No. of linearly independent columns

np.linalg.matrix_rank(mat_1)

3

In [19]:
## Inverse of a matrix only for those matrix whose determinant != 0 i.e non singular matrix.

np.linalg.inv(mat_1)

matrix([[-1.16836735,  0.35034014,  0.01020408],
        [ 0.58163265, -0.14965986,  0.01020408],
        [ 0.16836735, -0.0170068 , -0.01020408]])

In [20]:
## Solution of linear equations i.e unique, infinite and no solution.
## 2x + y+ 2z = 2
## 3x + 2y + 7z = -1
## 6x + 4y - 5z = 3
## Equation will be AX = B
## X = [x, y, z]
## Solve 'AB' matrix and resultant matrix will be X 

A = np.matrix("2, 1, 2; 3, 2, 7; 6, 4, -5")
B = np.matrix("2, -1, 3").T

print("Matrix A is :-\n", A)
print("\nMatrix B is :-\n", B)

Matrix A is :-
 [[ 2  1  2]
 [ 3  2  7]
 [ 6  4 -5]]

Matrix B is :-
 [[ 2]
 [-1]
 [ 3]]


In [21]:
print('The resultant X matrix of dependent variables is:- \n ', np.linalg.solve(A, B))

The resultant X matrix of dependent variables is:- 
  [[ 4.21052632]
 [-5.89473684]
 [-0.26315789]]
