# Numpy - Numerical Python

#### Import numpy package

In [1]:
 import numpy as np

#### Create an array

In [2]:
## numpy.array(object)
x = np.array([2, 3, 4,5])

a = np.array([[2,3,4], [5,6,8], [-3,-9,0]])
print(a)

[[ 2  3  4]
 [ 5  6  8]
 [-3 -9  0]]


#### Check type of  'x'

In [3]:
type(x)

numpy.ndarray

In [4]:
##Find shape of an array
a.shape

(3, 3)

#### Numpy can handle different categorical entities

In [5]:
x = np.array([2,69,'A',4])
print(x)

['2' '69' 'A' '4']


As per output, numpy will treat all elements with same datatype i.e string.

### Generate arrays using linspace() 

Returns equally spaced numbers within the given range based on the sample number.

Syntax: numpy.linspace(start, stop, no_of_samples, endpoint, dtype, return_increment)

In [6]:
##Endpoint inlude when it is True vice versa
np.linspace(start =77, stop=87, num =10, endpoint =True ,retstep=True)

(array([77.        , 78.11111111, 79.22222222, 80.33333333, 81.44444444,
        82.55555556, 83.66666667, 84.77777778, 85.88888889, 87.        ]),
 1.1111111111111112)

### Generate arrays using arange()

Returns equally spaced numbers with in the given range based on step size.

Syntax: numpy.arange(start, stop, step)

In [7]:
np.arange(start =69, stop=169, step=7)

array([ 69,  76,  83,  90,  97, 104, 111, 118, 125, 132, 139, 146, 153,
       160, 167])

### Generate arrays using ones()

Returns an array of given sahpe and type filled with ones.

Syntax: numpy.ones(shape, dtype(default: float))

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.ones((4,4), int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Generate arrays using zeros()

Returns an array of given shape and type filled with zeros.

Syntax: numpy.zeros(shape, dtype(default: float))

In [10]:
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Generate arrays using random.rand()

Returns an array of given shape filled with random values

Syntax: numpy.random.rand(shape)

In [11]:
print(np.random.rand(7))

[0.59513502 0.83135376 0.81648873 0.92644382 0.70288422 0.3977443
 0.37674393]


In [12]:
np.random.rand(3,3)

array([[0.14261569, 0.57269537, 0.68307546],
       [0.48233772, 0.65695167, 0.68109771],
       [0.12296282, 0.2593867 , 0.75519414]])

In [13]:
##Syntax: numpy.random.randint(start, stop, shape)
np.random.randint(1,10,(3,3))

array([[6, 4, 3],
       [6, 6, 2],
       [6, 1, 8]])

### Generate arrays using logspace

Returns equally spaced numbers based on log space

Syntax: numpy.logspace(start, stop, num_of_samples(deafult =50) , endpoint, base(default=10.0) , dtype)

In [14]:
np.logspace(4,40, num=5, endpoint =True, base=10.0)

array([1.e+04, 1.e+13, 1.e+22, 1.e+31, 1.e+40])

### Numpy is faster than python list

'timeit' module can be used to measure the execution time for snippets of code.

In [15]:
##Creating a list
x=range(1000)

In [16]:
##Calculate runtime speed of an python list
timeit sum(x)

118 µs ± 4.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
##Creating a numpy array
y = np.array(x)

In [22]:
timeit np.sum(y)

32.3 µs ± 735 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Numpy use less memory at  runtime

Compare list and numpy memory used in runtime

In [23]:
## Multiply the size of an individual element with the number of elements in list 
import sys
sys.getsizeof(1)*len(x)

14000

In [24]:
## Size of an array found by multiplying the size of an individual element with no_of elements in array.
y.itemsize * y.size

4000

### Reshape an array

Recasts an array to new shape without changing it's data

In [25]:
grid = np.arange(start=1, stop=13).reshape(4,3)
print(grid)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
grid.shape

(4, 3)

### Operations on numpy

Arthimetic operations like add, subtract & divide etc can be performed efficiently through numpy.

In [27]:
## Numpy addition
array_1 = np.array([[9,0,-3], [-69,343,-31323], [21,-423,323]])
array_2 = np.arange(start =11, stop=20).reshape(3,3)

print(array_1) 
print()
print(array_2)

[[     9      0     -3]
 [   -69    343 -31323]
 [    21   -423    323]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [28]:
print(np.add(array_1, array_2))

[[    20     12     10]
 [   -55    358 -31307]
 [    38   -405    342]]


In [29]:
##Numpy Multiplication

print(np.multiply(array_1, array_2))

[[     99       0     -39]
 [   -966    5145 -501168]
 [    357   -7614    6137]]


In [30]:
arr_3 =np.array([[19,16], [120,189]])
arr_4 =np.arange(start=2, stop=6).reshape(2,2)

In [31]:
##Numpy remainder :- Return element-wise remainder of division
np.remainder(arr_3, arr_4)

array([[1, 1],
       [0, 4]], dtype=int32)

### Accessing components of an array

Components of an array can be accessed by using index number

In [32]:
##Acess element having index (2,3) from array_1 and index starts from 0.
print(array_1)
print(array_1[2,2])

[[     9      0     -3]
 [   -69    343 -31323]
 [    21   -423    323]]
323


In [33]:
##Access elements of first row of an array
array_1[0,:]

##Access elements of first column of an array
array_1[:,0]

array([  9, -69,  21])

#### Modification & Extraction of arrays

In [34]:
##Subset 2X2 array of first rows & columns from array_1
array_1_sub = array_1[:2, :2]
print(array_1)
print()
print(array_1_sub)

[[     9      0     -3]
 [   -69    343 -31323]
 [    21   -423    323]]

[[  9   0]
 [-69 343]]


In [35]:
##Change value of an element in array_subset through its index
array_1_sub[0,0]=110

print(array_1_sub)

[[110   0]
 [-69 343]]


In [36]:
##Modifying value through subset array will change original array too.
print(array_1)

[[   110      0     -3]
 [   -69    343 -31323]
 [    21   -423    323]]


#### Transpose of an array

In [37]:
np.transpose(array_1)

array([[   110,    -69,     21],
       [     0,    343,   -423],
       [    -3, -31323,    323]])

#### Adding new row and column in array_1

In [38]:
## Modifying array using append() & axis = 0 for row or 1 for col  

np.append(array_1, [[9,289,-7]], axis=0)

array([[   110,      0,     -3],
       [   -69,    343, -31323],
       [    21,   -423,    323],
       [     9,    289,     -7]])

In [39]:
new_col =np.array([2,3,5]).reshape(3,1)
print(new_col)

[[2]
 [3]
 [5]]


In [40]:
arr_col =np.append(array_1, new_col, axis=1)
arr_col

array([[   110,      0,     -3,      2],
       [   -69,    343, -31323,      3],
       [    21,   -423,    323,      5]])

In [41]:
## Insert values at a given position and axis in an array
## numpy.insert(array, index_position, values, axis_row_ncol)

arr_ins =np.insert(array_1, 1, [1,2,3], axis=0)
print(array_1)
print()
print(arr_ins)

[[   110      0     -3]
 [   -69    343 -31323]
 [    21   -423    323]]

[[   110      0     -3]
 [     1      2      3]
 [   -69    343 -31323]
 [    21   -423    323]]


In [42]:
##Delete an row or column at given position in an array

arr_del = np.delete(array_1, 2, axis=0)
print(array_1)
print()
print(arr_del)

[[   110      0     -3]
 [   -69    343 -31323]
 [    21   -423    323]]

[[   110      0     -3]
 [   -69    343 -31323]]


#### To be continued....